### ISSUE TITLE
Images broken.

### ISSUE THREAD

**Issue by niflying** [DJI-Mobile-SDK-Tutorials/Android-VideoStreamDecodingSample#11]
Hi, I got a problem here .
my picture broken like this:
![screenshot_1487659132707](https://cloud.githubusercontent.com/assets/10345492/23154283/0a8b3dcc-f848-11e6-9b54-d11cc92d243b.jpg)

I run this project on P3S and android 4.4.4 phone

**Comment by ltluc253** [comment]
@niflying Is there anything new about this issue?

**Comment by dji-dev** [comment]
Will go ahead and close this ticket as current version should not have this problem any more.
Please feel free to reopen if the problem still exists.
Thanks!
