### ISSUE TITLE
精灵3P连接成功后点“OPEN”程序直接闪退

### ISSUE THREAD

**Issue by lqsheng** [DJI-Mobile-SDK-Tutorials/Android-VideoStreamDecodingSample#18]
不知道为何，直接git clone下来的，只改了KEY那部分，想看看示例工程的效果，然而精灵3P连接成功后点“OPEN”程序就直接闪退，用ADB调试按下“OPEN”后的logcat如下图：
![1](https://cloud.githubusercontent.com/assets/25112740/24986037/898bad28-202a-11e7-97f2-617f7d2d83af.jpg)
所用机型为 精灵3 Professional,手机型号是荣耀6PLUS，安卓6.0，CPU是armeabi-v7a架构，符合示例工程要求，工程的compileSdkVersion 是25

**Comment by lqsheng** [comment]
进一步发现问题是工程的targetSdkVersion 不能高于22，只要高于22就会发生闪退现象，设为22及22以下就正常了，可以正常预览画面，如图：
![dji1](https://cloud.githubusercontent.com/assets/25112740/24996013/bbb9175c-2063-11e7-96c1-ba89d01d49a2.png)
只是点了Screen shot后，保存下来的图片没有一张是正常的，质量最好的也是下面这样的:
![dji2](https://cloud.githubusercontent.com/assets/25112740/25008385/1bbfe9e6-2096-11e7-93e4-5383ebc850fd.jpg)
还有很多是下面这样的：
![dji4](https://cloud.githubusercontent.com/assets/25112740/25010482/d68b1722-209c-11e7-84d3-a779b5bf58ec.jpg)

**Comment by dji-dev** [comment]
Please use English when creating an issue
