### ISSUE TITLE
OSMO+ and the video stream decoding sample

### ISSUE THREAD

**Issue by Djacob502** [DJI-Mobile-SDK-Tutorials/Android-VideoStreamDecodingSample#21]
Can the video stream decoding sample work with the OSMO+? 

With the OSMO+ and using a texture view the video displays fine.

However, following the sample, displaying the video on a surface view - the video does not display correctly. Then when parsing the individual frames the program displays a blank frame. 

The same code works correctly with a phantom 4 pro. 

OMSO+
Android 7
nvidia k1 shield
Android studio 2.3.3

**Comment by dji-dev** [comment]
Will go ahead and close this ticket as current version should not have this problem.
Please feel free to reopen if the problem still exists.
Thanks!
