### ISSUE TITLE
I can't clone by using Android studio

### ISSUE THREAD

**Issue by jamesxienctu** [DJI-Mobile-SDK-Tutorials/Android-VideoStreamDecodingSample#4]
The error message is as follows:
https://drive.google.com/file/d/0B726Quay7lRDdHVEWVhhbzVnQUU/view

Please help solve it.

**Comment by oliverou** [comment]
Hi @jamesxienctu, please follow the README instruction of this Github Sample to download the sample project. Since some JNI lib files are too big, you should use Git LFS to download them.
