### ISSUE TITLE
Drone doesn't connect v 4.11

### ISSUE THREAD

**Issue by rabbishuki** [DJI-Mobile-SDK-Tutorials/Android-VideoStreamDecodingSample#60]
I updated the sample application to version 4.11 and it builds successfully.

Installed on my phone, plug in a P4A, and it doesn't connect.
A toast comes up saying "Disconnected".

I tried with Matrice 100 and got the same result.

Is the problem in your sample app? or does it have to do with Android x changes?

This is what it looks like, after connecting.
<img src="https://user-images.githubusercontent.com/24904197/68297481-b124cb00-009f-11ea-819e-5f780b16aff2.png" width="400" height="790">

**Comment by rabbishuki** [comment]
The problem was that updating the project deleted the SDK Key

**Comment by dji-dev** [comment]
Public comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/29615'>Zendesk ticket #29615</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
Great to hear that you have solved the problem by yourself.
Please feel free to contact us via the format once any problems.
https://formcrafts.com/a/dji-developer-feedback-en

Thanks,

Luce Luo
DJI Dev Team
