### ISSUE TITLE
Is the dji mavic air 2 supported

### ISSUE THREAD

**Issue by Consti10** [DJI-Mobile-SDK-Tutorials/Android-VideoStreamDecodingSample#67]
Hello,
Is the dji mavic air 2 supported with this example / are you going to add it ?
Since 
a) I cannot find is name string and 
b) It also uses h265

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/39693'>Zendesk ticket #39693</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
The Mavic air 2 will be supported in the MSDK 4.14, November 30, seeing the SDK roadmap.
https://developer.dji.com/user/roadmap/#msdk
​ ![](https://djisdksupport.zendesk.com/attachments/token/0FoB1h2QXyRl9Nl8USvT1kfMN/?name=%E6%88%AA%E5%B1%8F2020-10-01+%E4%B8%8B%E5%8D%883.02.27.png)​

Thanks,

Luce Luo
DJI Developer Support<br><a href='https://djisdksupport.zendesk.com/attachments/token/0FoB1h2QXyRl9Nl8USvT1kfMN' target='zd_attach'>截屏2020-10-01 下午3.02.27.png</a>
