### ISSUE TITLE
在自己的工程中使用so库需要重新进行编译吗？

### ISSUE THREAD

**Issue by yandong-111** [DJI-Mobile-SDK-Tutorials/Android-VideoStreamDecodingSample#68]
我想在自己的工程中使用ffmpeg编解码，需要去下载[https://github.com/dji-sdk/FFmpeg](url)然后重新编译so库文件吗？我将这个demo中的so文件直接复制进我的工程后报错：java.lang.UnsatisfiedLinkError: No implementation found for
另外DJIcodeManager本身在编解码时是否使用了GPU加速？

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/40405'>Zendesk ticket #40405</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
这个项目已经很旧没有维护了，不再建议使用，您可以网上查找更新版本ffmpeg相关集成方式自行集成。
DJIcodeManager本身在编解码时没有使用了GPU加速。

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持

**Comment by yandong-111** [comment]
明白了，感谢您的解答
