### ISSUE TITLE
Yuvdatacallback makes video freeze

### ISSUE THREAD

**Issue by gab933** [DJI-Mobile-SDK-Tutorials/Android-VideoStreamDecodingSample#83]
Hi,
in USE_TEXTURE_VIEW demo, when I click on yuv button, therefore activating yuvdatacallback, the video freezes.
How this can be avoided?
Actually I could draw a bitmap on textureview with video content, but I noticed it could be expensive in terms of processing.
Thank you,

Gabriele

**Comment by DJI-William** [comment]
This is the design, the video stream cannot be displayed while Yuv data is receiving. This cannot be avoided.
