### ISSUE TITLE
Will future Android SDK version be supported?

### ISSUE THREAD

**Issue by Andreas1331** [DJI-Mobile-SDK-Tutorials/Android-VideoStreamDecodingSample#86]
In order to be able to build using Gradle I had to downgrade my minimum Android SDK Version to 29 as seen in your project example. I don't see this mentioned anywhere in your documentation. Changing to version 30 will break it, but will future versions be supported?

(EDIT: I realise this is only for the WebRTC project, and I've posted the wrong place)

**Comment by neilyoung** [comment]
I'm not sure if this statement is correct. I was perfectly able to compile the app using minSdk 24 and targetSdk 30. Gradle is 7.3.3

**Comment by Andreas1331** [comment]
You are right. Upgrading Gradle allowed for increasing the SDK Target. Appreciate the help.

**Comment by neilyoung** [comment]
Thanks for confirmation
